# Generated by Django 4.1 on 2022-10-01 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='createlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=12)),
                ('assignment_name', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=50)),
                ('start', models.DateTimeField()),
                ('no_of_submissions', models.IntegerField()),
                ('perc_penalty', models.IntegerField()),
                ('first_sub_time', models.DateTimeField()),
                ('extend', models.CharField(max_length=5)),
                ('second_sub_time', models.DateTimeField()),
                ('notif', models.CharField(max_length=12)),
                ('neg_mark', models.CharField(max_length=12)),
                ('face_rec', models.CharField(max_length=12)),
                ('res_anno', models.CharField(max_length=100)),
                ('result_time', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.IntegerField()),
                ('R', models.JSONField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateAssignment.createlink')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=100)),
                ('rand_variable_min', models.IntegerField()),
                ('rand_variable_max', models.IntegerField()),
                ('explanation', models.TextField(blank=True, max_length=300)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateAssignment.createlink')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20)),
                ('college', models.TextField()),
                ('type', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True, max_length=500)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CreateAssignment.createlink')),
            ],
        ),
    ]
