# Generated by Django 3.2.8 on 2022-07-16 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=1, null=True)),
                ('question', models.TextField(null=True)),
                ('ans', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='questiondata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des1', models.TextField(blank=True)),
                ('des2', models.TextField(blank=True)),
                ('des3', models.TextField(blank=True)),
                ('des4', models.TextField(blank=True)),
                ('des5', models.TextField(blank=True)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='ques_img')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='ques_img')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='ques_img')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='ques_img')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='ques_img')),
                ('rmin1', models.IntegerField(default=1, null=True)),
                ('rmax1', models.IntegerField(default=100, null=True)),
                ('rmin2', models.IntegerField(default=100, null=True)),
                ('rmin3', models.IntegerField(default=1, null=True)),
                ('rmax3', models.IntegerField(default=100, null=True)),
                ('rmin4', models.IntegerField(default=1, null=True)),
                ('rmax4', models.IntegerField(default=100, null=True)),
                ('rmin5', models.IntegerField(default=1, null=True)),
                ('rmax5', models.IntegerField(default=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='createlink',
            name='extend',
        ),
        migrations.AlterField(
            model_name='createlink',
            name='course_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='createlink',
            name='first_sub_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='createlink',
            name='no_of_submissions',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='createlink',
            name='perc_penalty',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='createlink',
            name='result_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='createlink',
            name='second_sub_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='createlink',
            name='start',
            field=models.DateTimeField(blank=True),
        ),
        migrations.DeleteModel(
            name='Instruction',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='questiondata',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateAssignment.createlink'),
        ),
        migrations.AddField(
            model_name='instructions',
            name='assignm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CreateAssignment.createlink'),
        ),
        migrations.AddField(
            model_name='assignquestion',
            name='qno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateAssignment.createlink'),
        ),
    ]
