# Generated by Django 3.2.8 on 2022-07-16 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0002_auto_20220716_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignquestion',
            name='qno',
        ),
    ]
