# Generated by Django 3.2.8 on 2022-07-16 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0003_remove_assignquestion_qno'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignquestion',
            name='qno',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CreateAssignment.questiondata'),
        ),
    ]
