# Generated by Django 3.2.8 on 2022-07-16 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0005_auto_20220716_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignquestion',
            name='ans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignquestion',
            name='qno',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CreateAssignment.createlink'),
        ),
        migrations.AlterField(
            model_name='assignquestion',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
