# Generated by Django 3.2.8 on 2022-07-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0006_auto_20220716_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondata',
            name='des2',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='des3',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='des4',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='des5',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='rmax4',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='rmax5',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='rmin4',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='rmin5',
        ),
    ]
