# Generated by Django 3.2.8 on 2022-07-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0007_auto_20220716_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondata',
            name='ans1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='ans2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='ans3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='ans4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='ans5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='exp1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='exp2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='exp3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='exp4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='exp5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='mark1',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='mark2',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='mark3',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='mark4',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='mark5',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='ques1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='ques2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='ques3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='ques4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='ques5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
