# Generated by Django 3.2.8 on 2022-07-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0008_auto_20220717_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondata',
            name='rmax2',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='rmin2',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
