# Generated by Django 3.2.8 on 2022-07-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0010_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondata',
            name='ans2',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='ans3',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='ans4',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='ans5',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='exp2',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='exp3',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='exp4',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='exp5',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='mark2',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='mark3',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='mark4',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='mark5',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='ques2',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='ques3',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='ques4',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='ques5',
        ),
    ]
