# Generated by Django 3.2.8 on 2022-07-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0011_auto_20220718_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondata',
            name='rmax1',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='rmax2',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='rmin1',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='rmin2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
