# Generated by Django 3.2.8 on 2022-07-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0015_alter_questiondata_rmin2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondata',
            name='rmin2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
