# Generated by Django 3.2.8 on 2022-07-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0019_alter_questiondata_rmax2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondata',
            name='mark1',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='rmax3',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='rmin3',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
