# Generated by Django 3.2.8 on 2022-07-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0023_auto_20220721_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='assignquestion',
        ),
    ]
