# Generated by Django 3.2.8 on 2022-07-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0024_delete_assignquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.TextField(default=None),
        ),
    ]
