# Generated by Django 3.2.8 on 2022-07-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0025_profile_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.TextField(),
        ),
    ]
