# Generated by Django 3.2.8 on 2022-08-13 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0029_flipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='privacyflip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub', models.CharField(max_length=2)),
                ('flog', models.CharField(max_length=2)),
                ('fdomain', models.CharField(max_length=10)),
                ('fpass', models.CharField(max_length=10)),
                ('fpri', models.CharField(max_length=2)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateAssignment.flipping')),
            ],
        ),
    ]
