# Generated by Django 3.2.8 on 2022-08-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0030_privacyflip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privacyflip',
            old_name='flog',
            new_name='fprivacy',
        ),
        migrations.RemoveField(
            model_name='privacyflip',
            name='fpri',
        ),
        migrations.RemoveField(
            model_name='privacyflip',
            name='pub',
        ),
        migrations.AlterField(
            model_name='privacyflip',
            name='fdomain',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='privacyflip',
            name='fpass',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
