# Generated by Django 3.2.8 on 2022-08-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0031_auto_20220813_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacyflip',
            name='fdomain',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
