# Generated by Django 3.2.8 on 2022-08-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0032_alter_privacyflip_fdomain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='privacyflip',
            new_name='flipprivacy',
        ),
    ]
