# Generated by Django 3.2.8 on 2022-08-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0033_rename_privacyflip_flipprivacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipprivacy',
            name='fprivacy',
            field=models.CharField(default='b', max_length=2),
        ),
    ]
