# Generated by Django 3.2.8 on 2022-08-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0034_alter_flipprivacy_fprivacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipprivacy',
            name='fpass',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
