# Generated by Django 3.2.8 on 2022-08-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0035_alter_flipprivacy_fpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipping',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='flipupload'),
        ),
    ]
