# Generated by Django 3.2.8 on 2022-08-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0036_alter_flipping_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipping',
            name='ftime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
