# Generated by Django 3.2.8 on 2022-08-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0037_flipping_ftime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipping',
            name='ftime',
            field=models.DateTimeField(),
        ),
    ]
