# Generated by Django 3.2.8 on 2022-08-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0038_alter_flipping_ftime'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipping',
            name='fsub',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
