# Generated by Django 3.2.8 on 2022-08-14 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CreateAssignment', '0039_flipping_fsub'),
    ]

    operations = [
        migrations.CreateModel(
            name='flipcollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcollect', models.CharField(blank=True, max_length=10, null=True)),
                ('ftime', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateAssignment.flipping')),
            ],
        ),
    ]
