# Generated by Django 3.2.8 on 2022-08-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0041_alter_flipcollection_fcollect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipcollection',
            name='fcollect',
            field=models.CharField(default='n', max_length=2),
        ),
    ]
