# Generated by Django 3.2.8 on 2022-08-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0042_alter_flipcollection_fcollect'),
    ]

    operations = [
        migrations.CreateModel(
            name='flipcustomize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fskin', models.CharField(default='a', max_length=2)),
                ('flogo', models.ImageField(blank=True, null=True, upload_to='flip_logo')),
                ('fbg', models.ImageField(blank=True, null=True, upload_to='flip_bg')),
                ('fcpanel', models.CharField(default='#030000', max_length=10)),
                ('fcbg', models.CharField(default='#030000', max_length=10)),
                ('fclink', models.CharField(default='#030000', max_length=10)),
                ('ffavicon', models.ImageField(blank=True, null=True, upload_to='flip_favicon')),
                ('fobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateAssignment.flipping')),
            ],
        ),
    ]
