# Generated by Django 3.2.8 on 2022-09-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0044_flippass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipcustomize',
            name='fcpanel',
            field=models.CharField(max_length=10),
        ),
    ]
