# Generated by Django 3.2.8 on 2022-09-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0046_auto_20220904_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipcustomize',
            name='fcbg',
            field=models.CharField(default='#14e12c', max_length=10),
        ),
        migrations.AlterField(
            model_name='flipcustomize',
            name='fclink',
            field=models.CharField(default='#14e12c', max_length=10),
        ),
        migrations.AlterField(
            model_name='flipcustomize',
            name='fcpanel',
            field=models.CharField(default='#14e12c', max_length=10),
        ),
        migrations.AlterField(
            model_name='flipcustomize',
            name='fskin',
            field=models.CharField(default='#14e12c', max_length=2),
        ),
    ]
