# Generated by Django 3.2.8 on 2022-09-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0047_auto_20220904_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipcustomize',
            name='fweb',
            field=models.URLField(default='https://aim2crack.in/', max_length=100),
        ),
    ]
