# Generated by Django 3.2.8 on 2022-09-04 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0048_alter_flipcustomize_fweb'),
    ]

    operations = [
        migrations.CreateModel(
            name='flipviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdate', models.DateTimeField()),
                ('fobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateAssignment.flipping')),
            ],
        ),
    ]
