# Generated by Django 3.2.8 on 2022-09-08 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CreateAssignment', '0049_flipviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogo', models.ImageField(blank=True, null=True, upload_to='brand_logo')),
                ('bname', models.CharField(default='Aim2crack', max_length=10)),
                ('bweb', models.URLField(default='https://aim2crack.in/', max_length=100)),
                ('bfavicon', models.ImageField(blank=True, null=True, upload_to='brand_favicon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
