# Generated by Django 3.2.8 on 2022-10-16 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0050_branding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flipcollection',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='flipcollection',
            name='fobj',
        ),
        migrations.RemoveField(
            model_name='flipcustomize',
            name='fobj',
        ),
        migrations.RemoveField(
            model_name='flippass',
            name='fobj',
        ),
        migrations.RemoveField(
            model_name='flipping',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='flipprivacy',
            name='link',
        ),
        migrations.RemoveField(
            model_name='flipviews',
            name='fobj',
        ),
        migrations.DeleteModel(
            name='branding',
        ),
        migrations.DeleteModel(
            name='flipcollection',
        ),
        migrations.DeleteModel(
            name='flipcustomize',
        ),
        migrations.DeleteModel(
            name='flippass',
        ),
        migrations.DeleteModel(
            name='flipping',
        ),
        migrations.DeleteModel(
            name='flipprivacy',
        ),
        migrations.DeleteModel(
            name='flipviews',
        ),
    ]
